[teleop] Added custom preset feature on ERD/ES gui
tabiosg/mrover-workspace pull request #8
Opened 2022-03-13 17:54 UTC by catkims

<img width="523" alt="image" src="https://user-images.githubusercontent.com/79539806/158072577-0678907b-2cb9-4374-a855-c042752455a3.png">

2022-03-13 19:44 UTC, CameronTressler commented on base_station/gui/src/components/IKControls.vue
> +                 Button number: <input type='message' v-model ='buttonInc'>
Can we call this buttonIdx or something related to 'index' since it's not meant for incrementing?

2022-03-13 19:45 UTC, CameronTressler commented on base_station/gui/src/components/IKControls.vue
> +                 Button number: <input type='message' v-model ='buttonInc'>
Referring to the variable buttonInc

2022-03-13 19:46 UTC, CameronTressler commented on base_station/gui/src/components/IKControls.vue
> +            }
We can just call publish once at the bottom and pass this.name instead of this.button<x> right? (To avoid code duplication)

2022-03-13 19:51 UTC, CameronTressler commented on jetson/ra_kinematics/mrover_arm.cpp
> +
Is there a reason this function can't be a member of the parent class instead of the children?

2022-03-13 19:52 UTC, CameronTressler commented on rover_msgs/CustomPreset.lcm
> +}
nitpick can you add a newline at the end of this file

2022-03-13 19:54 UTC, CameronTressler requested changes
See comments

2022-03-17 00:06 UTC, CameronTressler approved these changes

2022-03-17 05:08 UTC, bli76 approved these changes

2022-03-17 21:10 UTC, tabiosg commented
Hi can someone resolve the conflict before I merge this in?

2022-03-17 21:12 UTC, catkims commented
Resolved

2022-03-17 21:15 UTC, merged